/**
 * Problem:
 *
 * Each new term in the Fibonacci sequence is generated by
 * adding the previous two terms. By starting with 1 and 2,
 * the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose
 * values do not exceed four million, find the sum of the
 * even-valued terms.
 */

console.time('Problem 2');

 let termOne = 1;
let termTwo = 2;
let nextTerm = termOne + termTwo;

let total = 0;

while (termTwo < 4000000) {
  if (termTwo % 2 === 0) {
    total += termTwo;
  }

  nextTerm = termOne + termTwo;
  termOne = termTwo;
  termTwo = nextTerm;
}

console.timeEnd('Problem 2');

console.log(`Total: ${total}`);
