/**
 * Problem:
 *
 * Each new term in the Fibonacci sequence is generated by
 * adding the previous two terms. By starting with 1 and 2,
 * the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose
 * values do not exceed four million, find the sum of the
 * even-valued terms.
 */

let term_1 = 1;
let term_2 = 2;
let next_term = term_1 + term_2;

let total = 0;

while (term_2 < 4000000) {
    if (term_2 % 2 == 0) {
        total += term_2
    }

    next_term = term_1 + term_2;
    term_1 = term_2;
    term_2 = next_term;
}

console.log("Total: " + total);